name: Fetch GitHub MetaData

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'  # Adjust to the appropriate Node.js version

      - name: Fetch GitHub Repos
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        run: |
          node ./action/fetch-data.js

      - name: Configure Git
        run: |
          git config --global user.name 'iamspdarsan'
          git config --global user.email 'iamspdarsan@gmail.com'

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        run: |
          git add ghmeta.json
          git commit -m 'Update ghmeta.json with latest GitHub data'
          git push
